version: '3.8'
services:
  react-app:
    build:
      context: ./awesome-fe
      dockerfile: Dockerfile
    ports:
      - "80:80" # Map container port 80 to host port 80
    depends_on:
      - swiftcloud

  swiftcloud:
    build:
      context: ./swiftcloud
    ports:
      - "4000:4000"
    volumes:
      - ./swiftcloud/:/app
    depends_on:
      - mysql-db
    restart: on-failure:10
    

  # MySQL Database
  mysql-db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: l;ylfu=k;F]d
      MYSQL_DATABASE: song
      MYSQL_USER: sqluser
      MYSQL_PASSWORD: lkpohelkp],
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init_sql:/docker-entrypoint-initdb.d

volumes:
  mysql-data: